### ISSUE TITLE
porting minonnect library from version 3.0 to version 4.3.1 as we are using new tisdk(texas instrument) 8.2.0.24

### ISSUE THREAD

**Issue by mkphsnbng** [mindsphere/mindconnect-lib#14]
We have downloaded minconnect lib from the link https://github.com/mindsphere/mindconnect-lib
and we are following the https://documentation.mindsphere.io/MindSphere/resources/mindconnect-lib-v4/resources-mclib-migration-guide.html

Example:
In version 3.0 we have used mcl_store_new_time_series(store, timeseries_version,
                        configuration_id, NULL, &time_series); in the migration steps its mentioned that we have to use mcl_timeseries_initialize() and mcl_timeseries_set_parameter() this means we have to replace version 3.0 api  mcl_store_new_time_series(store, timeseries_version,
                        configuration_id, NULL, &time_series); with version 4.3.2 2 API's like mcl_timeseries_initialize() and mcl_timeseries_set_parameter() as 2 different api's?

 how can we map the arguments from version 3 to version 4 apis's
Similarty how can we use the same parameters in version 4 of minconnect..

there are other api which we need clariffications to use like 
mcl_communication_exchange(communication, store,NUll) in version 3 and in version 4 mcl_connectivity_exchange() how can we map?

Below are the other API which we need clarifications?

| v3.0                                          | v4.3.2                                                    |
| --------------------------------------------- | --------------------------------------------------------- |
| mcl_configuration_initialize(&configuration)       | mcl_connectivity_configuration_initialize(&connectivity_configuration) (Replaced)       |
| configuration->proxy_hostname       |  mcl_core_configuration_set_parameter() (Replaced)       |
| mcl_communication_initialize(configuration, &communication)     | mcl_core_initialize (core_configuration, &core) and mcl_connectivity_initialize(connectivity_configuration, &connectivity ) (Replaced)       |
|mcl_communication_exchange(communication, store,NULL)      | mcl_connectivity_exchange(communication, store, NULL); (Replaced)       |
| mcl_store_new_data_source_configuration       | mcl_data_source_configuration_initialize (Replaced)       |
| mcl_data_source_configuration_get_id          | Not Available to find similar API                         |
| mcl_data_source_configuration_add_data_source | mcl_data_source_configuration_add_data_source (Available) |
| mcl_data_source_configuration_add_data_point  | Not Available to find similar API                         |
| mcl_log_util_set_output_level                 | Not Available to find similar API                         |
| mcl_log_util_finalize                         | Not Available to find similar API                         |
| mcl_store_new_time_series                     | Not Available to find similar API                         |
| mcl_time_series_new_value_set                 | Not Available to find similar API                         |
| mcl_time_series_add_value                     | Not Available to find similar API                         |
| mcl_communication_exchange                    | Not Available to find similar API                         |
| mcl_communication_destroy                     | Not Available to find similar API                         |
| mcl_configuration_initialize                  | Not Available to find similar API                         |

please provide the document if any

**Comment by siemens-developer** [comment]
Please follow the migration guide. 
https://documentation.mindsphere.io/MindSphere/resources/mindconnect-lib-v4/resources-mclib-migration-guide.html
